import { expect, test } from "@playwright/test";

test("프로젝트 profile은 분석·draft 저장·특정 version 활성화를 분리하고 지연을 즉시 표시한다", async ({ page }) => {
  const mutations: Array<{ path: string; body: any; csrf: string | undefined }> = [];
  let shadowReads = 0;
  let profiles: any[] = [];
  await page.route("**/api/**", async (route) => {
    const url = new URL(route.request().url()); const method = route.request().method(); const pathname = url.pathname;
    if (pathname === "/api/projects/13/profile-draft" && method === "POST") {
      await new Promise((resolve) => setTimeout(resolve, 350));
      await route.fulfill({ json: { draft: {
        name: "myagent implementation", taskKind: "implementation", warnings: ["CLAUDE.md import 불일치"],
        configSnapshot: { schemaVersion: 1, taskKind: "implementation", profileTemplate: { id: "wam-provider-runtime", source: "registered_project_catalog" }, runtime: { provider: "claude" }, permissions: { sandbox: "workspace-write" }, instructions: { files: ["AGENTS.md", "CLAUDE.md"] }, verification: { steps: [{ kind: "full_test", argv: ["npm", "test"], required: true }] }, protectedActions: ["deploy"] },
      } } }); return;
    }
    if (pathname === "/api/projects/13/profiles" && method === "POST") { mutations.push({ path: pathname, body: JSON.parse(route.request().postData() || "{}"), csrf: route.request().headers()["x-csrf-token"] }); await new Promise((resolve) => setTimeout(resolve, 350)); profiles = [{ id: "profile-1", name: "myagent implementation", taskKind: "implementation", status: "draft", activeVersion: null, versions: [{ id: "version-1", version: 1, configSnapshot: mutations[0].body.configSnapshot, note: "owner review" }] }]; await route.fulfill({ status: 201, json: { profile: profiles[0] } }); return; }
    if (pathname === "/api/projects/13/profiles/profile-1/activate" && method === "POST") { mutations.push({ path: pathname, body: JSON.parse(route.request().postData() || "{}"), csrf: route.request().headers()["x-csrf-token"] }); await new Promise((resolve) => setTimeout(resolve, 350)); profiles[0].status = "active"; profiles[0].activeVersion = 1; await route.fulfill({ json: { profile: profiles[0] } }); return; }
    if (pathname === "/api/projects/13/profiles") { await route.fulfill({ json: { profiles } }); return; }
    if (pathname === "/api/admin/providers/codex/shadow") { shadowReads += 1; await new Promise((resolve) => setTimeout(resolve, 350)); await route.fulfill({ json: { enabled: true, mode: "read_only_shadow", readiness: { scope: "thread_status_and_turn_history", status: "not_ready", reasons: ["insufficient_days", "mismatch_observed", "turn_insufficient_days", "turn_terminal_pair_missing"], interactiveCandidateEnabled: false, interactiveCandidateCohort: null, interactiveCandidateMaxNewChats: 0, candidateEligible: false, candidateBlockers: ["thread_status_shadow_not_ready", "turn_history_shadow_not_ready", "interactive_transport_candidate_flag_required"], transitionEligible: false, transitionBlockers: ["thread_status_shadow_not_ready", "turn_history_shadow_not_ready", "interactive_transport_candidate_flag_required"], threadStatus: { status: "not_ready", reasons: ["insufficient_days", "mismatch_observed"], metrics: { observedDays: 3, observations: 45, observedChats: 1, eligibleChats: 2, busySamples: 20, idleSamples: 25, p95LatencyMs: 123 } }, turnHistory: { status: "not_ready", reasons: ["turn_insufficient_days", "turn_terminal_pair_missing"], metrics: { observedDays: 3, scans: 44, pairedTurns: 7, terminalTurns: 8, missingPairs: 1, invalidTurns: 0, p95LatencyMs: 130 } } } } }); return; }
    if (pathname === "/api/admin/project-profiles/readiness") { await new Promise((resolve) => setTimeout(resolve, 350)); await route.fulfill({ json: { readiness: { totalProjects: 1, readyProjects: 0, requiredTaskKinds: ["analysis", "implementation"], projects: [{ projectId: 13, projectName: "myagent", ready: false, taskKinds: [{ taskKind: "analysis", issues: ["active_profile_missing"] }, { taskKind: "implementation", issues: profiles[0]?.status === "active" ? [] : ["active_profile_missing"] }], detectedWarnings: ["CLAUDE.md import 불일치"], detectedScripts: ["test"] }] } } }); return; }
    if (pathname === "/api/auth/sessions") { await route.fulfill({ json: { sessions: [], hasMore: false } }); return; }
    if (pathname === "/api/auth/mfa") { await route.fulfill({ json: { enabled: false, recoveryCodesRemaining: 0 } }); return; }
    const responses: Record<string, unknown> = { "/api/auth/me": { user: { id: 1, username: "admin", role: "admin", access_scope: "standard" }, csrfToken: "profile-csrf", temporary: false }, "/api/providers": { providers: [] }, "/api/projects": { projects: [{ id: 13, name: "myagent", path: "/workspace/myagent", chat_count: 0 }], defaultPath: "/workspace" }, "/api/chats": { chats: [] }, "/api/usage": { usage: [] }, "/api/system": { latest: null }, "/api/runtime": {}, "/api/slack": { enabled: false }, "/api/ntfy": { enabled: false }, "/api/approvals": { approvals: [] }, "/api/admin/slack-settings": {}, "/api/admin/ntfy-settings": {}, "/api/admin/idle-chat-settings": {}, "/api/admin/full-backups": { backups: [] }, "/api/remote-workers": { hosts: [] }, "/api/remote-worker-mappings": { mappings: [] } };
    await route.fulfill({ json: responses[pathname] ?? {} });
  });
  page.on("dialog", (dialog) => dialog.accept()); await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/");
  await page.getByRole("button", { name: "더보기", exact: true }).click(); await page.getByRole("dialog", { name: "더보기" }).getByRole("button", { name: /설정/ }).click();
  await expect(page.getByText("전체 준비 0/1", { exact: true })).toBeVisible(); await expect(page.getByText(/활성 profile 없음/)).toBeVisible();
  await page.getByLabel("Profile provider").selectOption("claude"); const analyze = page.getByRole("button", { name: "초안 분석" });
  const feedback = await analyze.evaluate((button) => new Promise<number>((resolve) => { const started = performance.now(); const observer = new MutationObserver(() => { if ((button as HTMLButtonElement).disabled && button.textContent?.includes("분석 중")) { observer.disconnect(); resolve(performance.now() - started); } }); observer.observe(button, { attributes: true, childList: true, subtree: true }); (button as HTMLButtonElement).click(); }));
  expect(feedback).toBeLessThan(500); await expect(page.getByText("CLAUDE.md import 불일치", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Profile 설정 JSON")).toHaveValue(/wam-provider-runtime/);
  await page.getByLabel("검토 메모").fill("owner review"); await page.getByRole("button", { name: "Draft 저장" }).click(); await expect(page.getByText(/활성화 전에는 새 채팅에 적용되지 않습니다/)).toBeVisible();
  expect(profiles[0].activeVersion).toBeNull(); await page.getByRole("button", { name: "명시 활성화" }).click(); await expect(page.getByRole("button", { name: "활성", exact: true })).toBeDisabled();
  expect(mutations).toEqual([{ path: "/api/projects/13/profiles", body: expect.objectContaining({ name: "myagent implementation", taskKind: "implementation", note: "owner review" }), csrf: "profile-csrf" }, { path: "/api/projects/13/profiles/profile-1/activate", body: { versionId: "version-1" }, csrf: "profile-csrf" }]);
  await expect(page.getByText("상태 일수 3/7", { exact: false })).toBeVisible(); await expect(page.getByText("turn 일수 3/7", { exact: false })).toBeVisible(); await expect(page.getByText("종료 pair 7/8", { exact: false })).toBeVisible(); await expect(page.getByText("상태 불일치 발견", { exact: true })).toBeVisible(); await expect(page.getByText("시작 없는 종료 turn 발견", { exact: true })).toBeVisible(); await expect(page.getByText(/대화형 후보 flag: 꺼짐/)).toBeVisible();
  const initialShadowReads = shadowReads;
  const refresh = page.getByRole("button", { name: "Readiness 새로고침" });
  const refreshFeedback = await refresh.evaluate((button) => new Promise<number>((resolve) => { const started = performance.now(); const observer = new MutationObserver(() => { if ((button as HTMLButtonElement).disabled && button.textContent?.includes("계산 중")) { observer.disconnect(); resolve(performance.now() - started); } }); observer.observe(button, { attributes: true, childList: true, subtree: true }); (button as HTMLButtonElement).click(); }));
  expect(refreshFeedback).toBeLessThan(500); await expect(page.getByRole("button", { name: "Readiness 새로고침" })).toBeEnabled(); expect(shadowReads).toBe(initialShadowReads + 1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
});
